#mybot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000


  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 200.0, i: 0.0, d: 0.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 10.0, i: 0.0, d: 0.0, i_clamp: 0.2}
#  joint3_position_controller:
#    type: effort_controllers/JointPositionController
#    joint: joint3
#    pid: {p: 2000.0, i: 2.0, d: 0}